export enum AllowlistOperationCode {
  CREATE_ALLOWLIST = 'CREATE_ALLOWLIST',
  GET_COLLECTION_TRANSFERS = 'GET_COLLECTION_TRANSFERS',

  CREATE_TOKEN_POOL = 'CREATE_TOKEN_POOL',
  CREATE_CUSTOM_TOKEN_POOL = 'CREATE_CUSTOM_TOKEN_POOL',
  CREATE_WALLET_POOL = 'CREATE_WALLET_POOL',

  ADD_PHASE = 'ADD_PHASE',

  ADD_COMPONENT = 'ADD_COMPONENT',
  COMPONENT_ADD_SPOTS_TO_ALL_ITEM_WALLETS = 'COMPONENT_ADD_SPOTS_TO_ALL_ITEM_WALLETS',
  COMPONENT_ADD_SPOTS_TO_WALLETS_EXCLUDING_CERTAIN_COMPONENTS = 'COMPONENT_ADD_SPOTS_TO_WALLETS_EXCLUDING_CERTAIN_COMPONENTS',
  COMPONENT_SELECT_RANDOM_WALLETS = 'COMPONENT_SELECT_RANDOM_WALLETS',
  COMPONENT_SELECT_RANDOM_PERCENTAGE_WALLETS = 'COMPONENT_SELECT_RANDOM_PERCENTAGE_WALLETS',

  ADD_ITEM = 'ADD_ITEM',
  ITEM_EXCLUE_TOKEN_IDS = 'ITEM_EXCLUE_TOKEN_IDS',
  ITEM_SELECT_TOKEN_IDS = 'ITEM_SELECT_TOKEN_IDS',
  ITEM_REMOVE_FIRST_N_TOKENS = 'ITEM_REMOVE_FIRST_N_TOKENS',
  ITEM_REMOVE_LAST_N_TOKENS = 'ITEM_REMOVE_LAST_N_TOKENS',
  ITEM_SELECT_FIRST_N_TOKENS = 'ITEM_SELECT_FIRST_N_TOKENS',
  ITEM_SELECT_LAST_N_TOKENS = 'ITEM_SELECT_LAST_N_TOKENS',
  ITEM_SORT_WALLETS_BY_TOTAL_TOKENS_COUNT = 'ITEM_SORT_WALLETS_BY_TOTAL_TOKENS_COUNT',
  ITEM_SORT_WALLETS_BY_UNIQUE_TOKENS_COUNT = 'ITEM_SORT_WALLETS_BY_UNIQUE_TOKENS_COUNT',
  ITEM_REMOVE_FIRST_N_WALLETS = 'ITEM_REMOVE_FIRST_N_WALLETS',
  ITEM_SELECT_FIRST_N_WALLETS = 'ITEM_SELECT_FIRST_N_WALLETS',
  ITEM_REMOVE_WALLETS_FROM_CERTAIN_COMPONENTS = 'ITEM_REMOVE_WALLETS_FROM_CERTAIN_COMPONENTS',

  ITEM_SORT_WALLETS_BY_MEMES_TDH = 'ITEM_SORT_WALLETS_BY_MEMES_TDH',
  TRANSFER_POOL_CONSOLIDATE_WALLETS = 'TRANSFER_POOL_CONSOLIDATE_WALLETS',
  TOKEN_POOL_CONSOLIDATE_WALLETS = 'TOKEN_POOL_CONSOLIDATE_WALLETS',
  ITEM_REMOVE_WALLETS_FROM_CERTAIN_TOKEN_POOLS = 'ITEM_REMOVE_WALLETS_FROM_CERTAIN_TOKEN_POOLS',
  MAP_RESULTS_TO_DELEGATED_WALLETS = 'MAP_RESULTS_TO_DELEGATED_WALLETS',
  ITEM_SELECT_WALLETS_OWNING_TOKEN_IDS = 'ITEM_SELECT_WALLETS_OWNING_TOKEN_IDS',
  // Placeholder for future operations (please keep this comment here, it's used by the code generator)
}

export enum AllowlistOperationType {
  OVERALL = 'OVERALL',
  TRANSFER_POOLS = 'TRANSFER_POOLS',
  TRANSFER_POOL = 'TRANSFER_POOL',
  TOKEN_POOLS = 'TOKEN_POOLS',
  TOKEN_POOL = 'TOKEN_POOL',
  CUSTOM_POOLS = 'CUSTOM_POOLS',
  CUSTOM_POOL = 'CUSTOM_POOL',
  WALLET_POOLS = 'WALLET_POOLS',
  WALLET_POOL = 'WALLET_POOL',
  PHASES = 'PHASES',
  PHASE = 'PHASE',
  COMPONENTS = 'COMPONENTS',
  COMPONENT = 'COMPONENT',
  ITEMS = 'ITEMS',
  ITEM = 'ITEM',
}
