export enum AllowlistOperationCode {
  CREATE_ALLOWLIST = 'CREATE_ALLOWLIST',
  GET_COLLECTION_TRANSFERS = 'GET_COLLECTION_TRANSFERS',

  CREATE_TOKEN_POOL = 'CREATE_TOKEN_POOL',
  CREATE_CUSTOM_TOKEN_POOL = 'CREATE_CUSTOM_TOKEN_POOL',
  CREATE_WALLET_POOL = 'CREATE_WALLET_POOL',

  ADD_PHASE = 'ADD_PHASE',

  ADD_COMPONENT = 'ADD_COMPONENT',
  COMPONENT_ADD_SPOTS_TO_ALL_ITEM_WALLETS = 'COMPONENT_ADD_SPOTS_TO_ALL_ITEM_WALLETS',

  ADD_ITEM = 'ADD_ITEM',
  ITEM_EXCLUE_TOKEN_IDS = 'ITEM_EXCLUE_TOKEN_IDS',
  ITEM_SELECT_TOKEN_IDS = 'ITEM_SELECT_TOKEN_IDS',
  ITEM_REMOVE_FIRST_N_TOKENS = 'ITEM_REMOVE_FIRST_N_TOKENS',
  ITEM_REMOVE_LAST_N_TOKENS = 'ITEM_REMOVE_LAST_N_TOKENS',
  // Placeholder for future operations (please keep this comment here, it's used by the code generator)
}
