export enum AllowlistOperationCode {
  CREATE_ALLOWLIST = 'CREATE_ALLOWLIST',
  GET_COLLECTION_TRANSFERS = 'GET_COLLECTION_TRANSFERS',

  CREATE_TOKEN_POOL = 'CREATE_TOKEN_POOL',
  CREATE_CUSTOM_TOKEN_POOL = 'CREATE_CUSTOM_TOKEN_POOL',
  CREATE_WALLET_POOL = 'CREATE_WALLET_POOL',

  ADD_PHASE = 'ADD_PHASE',

  ADD_COMPONENT = 'ADD_COMPONENT',

  ADD_ITEM = 'ADD_ITEM',
  ITEM_EXCLUE_TOKEN_IDS = 'ITEM_EXCLUE_TOKEN_IDS',
  ITEM_SELECT_TOKEN_IDS = 'ITEM_SELECT_TOKEN_IDS',
}
