import { Time } from '../../time';

export interface CommonTdhInfo {
  readonly wallet: string;
  readonly block: number;
  readonly tdh_rank: number;
  readonly tdh: number;
  readonly boost: number;
  readonly boosted_tdh: number;
  readonly tdh__raw: number;
  readonly balance: number;
  readonly memes_cards_sets: number;
  readonly genesis: number;
  readonly unique_memes: number;
  readonly memes_tdh: number;
  readonly memes_tdh__raw: number;
  readonly memes_balance: number;
  readonly memes_tdh_season1: number;
  readonly memes_tdh_season1__raw: number;
  readonly memes_tdh_season2: number;
  readonly memes_tdh_season2__raw: number;
  readonly memes: {
    id: number;
    tdh: number;
    balance: number;
    tdh__raw: number;
  }[];
  readonly memes_ranks: { id: number; rank: number }[];
  readonly gradients_tdh: number;
  readonly gradients_tdh__raw: number;
  readonly gradients_balance: number;
  readonly gradients: { id: number; rank: number }[];
  readonly gradients_ranks: { id: number; rank: number }[];
  readonly boosted_memes_tdh_season1: number;
  readonly boosted_memes_tdh_season2: number;
  readonly boosted_gradients_tdh: number;
  readonly tdh_rank_memes: number;
  readonly tdh_rank_memes_szn1: number;
  readonly tdh_rank_memes_szn2: number;
  readonly tdh_rank_gradients: number;
  readonly tdh_rank_memes_szn3: number;
  readonly unique_memes_season1: number;
  readonly unique_memes_season2: number;
  readonly unique_memes_season3: number;
  readonly boosted_memes_tdh_season3: number;
  readonly memes_tdh_season3: number;
  readonly memes_tdh_season3__raw: number;
  readonly boosted_memes_tdh: number;
  readonly created_at: Time;
  readonly memes_balance_season1: number;
  readonly memes_balance_season2: number;
  readonly memes_balance_season3: number;
  readonly purchases_value: number;
  readonly purchases_count: number;
  readonly purchases_value_primary: number;
  readonly purchases_count_primary: number;
  readonly purchases_value_secondary: number;
  readonly purchases_count_secondary: number;
  readonly sales_value: number;
  readonly sales_count: number;
  readonly transfers_in: number;
  readonly transfers_out: number;
  readonly purchases_value_memes: number;
  readonly purchases_count_memes: number;
  readonly purchases_value_memes_season1: number;
  readonly purchases_count_memes_season1: number;
  readonly purchases_value_memes_season2: number;
  readonly purchases_count_memes_season2: number;
  readonly purchases_value_memes_season3: number;
  readonly purchases_count_memes_season3: number;
  readonly purchases_value_gradients: number;
  readonly purchases_count_gradients: number;
  readonly purchases_value_primary_memes: number;
  readonly purchases_count_primary_memes: number;
  readonly purchases_value_primary_memes_season1: number;
  readonly purchases_count_primary_memes_season1: number;
  readonly purchases_value_primary_memes_season2: number;
  readonly purchases_count_primary_memes_season2: number;
  readonly purchases_value_primary_memes_season3: number;
  readonly purchases_count_primary_memes_season3: number;
  readonly purchases_value_primary_gradients: number;
  readonly purchases_count_primary_gradients: number;
  readonly purchases_value_secondary_memes: number;
  readonly purchases_count_secondary_memes: number;
  readonly purchases_value_secondary_memes_season1: number;
  readonly purchases_count_secondary_memes_season1: number;
  readonly purchases_value_secondary_memes_season2: number;
  readonly purchases_count_secondary_memes_season2: number;
  readonly purchases_value_secondary_memes_season3: number;
  readonly purchases_count_secondary_memes_season3: number;
  readonly purchases_value_secondary_gradients: number;
  readonly purchases_count_secondary_gradients: number;
  readonly sales_value_memes: number;
  readonly sales_count_memes: number;
  readonly sales_value_memes_season1: number;
  readonly sales_count_memes_season1: number;
  readonly sales_value_memes_season2: number;
  readonly sales_count_memes_season2: number;
  readonly sales_value_memes_season3: number;
  readonly sales_count_memes_season3: number;
  readonly sales_value_gradients: number;
  readonly sales_count_gradients: number;
  readonly transfers_in_memes: number;
  readonly transfers_out_memes: number;
  readonly transfers_in_memes_season1: number;
  readonly transfers_out_memes_season1: number;
  readonly transfers_in_memes_season2: number;
  readonly transfers_out_memes_season2: number;
  readonly transfers_in_memes_season3: number;
  readonly transfers_out_memes_season3: number;
  readonly transfers_in_gradients: number;
  readonly transfers_out_gradients: number;
  readonly transaction_reference: Time;
}

export interface TdhInfo extends CommonTdhInfo {
  readonly ens?: string;
}

export interface ConsolidatedTdhInfo extends CommonTdhInfo {
  readonly consolidation_display: string;
  readonly wallets: string[];
}
