name: Allowlist Ci

on:
  push:
    branches:
      - main

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run unit tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
      - name: Notify about failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          with:
            title: "allowlist-lib build is broken in master"
            color: 0xff0000
